export 'package:flutter_evento/screens/create_evento_screen.dart';
export 'package:flutter_evento/screens/google_map_screen.dart';
export 'package:flutter_evento/screens/list_eventos_screen.dart';
export 'package:flutter_evento/screens/animated_screen.dart';
export 'package:flutter_evento/screens/alert_screen.dart';
export 'package:flutter_evento/screens/avatar_screen.dart';
export 'package:flutter_evento/screens/home_screen.dart';
export 'package:flutter_evento/screens/listview1_screen.dart';
export 'package:flutter_evento/screens/listview2_screen.dart';
